### ISSUE TITLE
Thesis.pdf is empty

### ISSUE THREAD

**Issue by sekael** [kurtkuehnert/terrain_renderer#1]
Hi @kurtkuehnert,

first of all, thank you for sharing your extensive work on terrain rendering with bevy here on GitHub! I am currently experimenting with the game engine for doing exactly the same as you did: rendering swisstopo DEMs. 
Thus, I am very intrigued by your work and would love to follow up on more details on your implementation. Unfortunately, the pdf-version of your bachelor thesis only contains a single empty white page. If it is not too much to ask, I would be very interested in reading more about your work and implementation and would appreciate it greatly if you could provide me with the thesis paper! 

Thank you and best regards!

**Comment by kurtkuehnert** [comment]
I appreciate your interest. 
I am not permitted to release my thesis publically yet. First, it has to be reviewed by my University.
But if you would like, I can send you a copy in private.
You could join my Discord Server or email me (link on my profile).

**Comment by kurtkuehnert** [comment]
The Thesis is now uploaded. :)
